### ISSUE TITLE
Clarify that index in graphemeLenAt does not count graphemes

### ISSUE THREAD

**Issue by eugenesvk** [nitely/nim-graphemes#14]
At first reading of your module description I thought that the second parameter of `graphemeLenAt` — the index — imlies a grapheme order, so this code snippet should've given the length in bytes of each grapheme in a string
```
let grTestString = "u̲n̲d̲e̲r̲"
for i in 0..graphemesCount(grTestString)-1:
  echo graphemeLenAt(grTestString, i)
```
However, this output suggests that the index is a byte index as it gives 3,2,1 for the first 3-byte grapheme before indexing over the second?
```
3
2
1
3
2
```
If this is as intended, would you please clarify in the docs that this is not an index of graphemes? Or maybe would it be more "intuitive" to have this an index of graphemes?

**Comment by nitely** [comment]
Yes, the index is at byte. The doc does imply that: `Return the number of bytes in the grapheme starting at s[i]`, where `s`  is a string and `i` is an index of the string, but a clarification is welcome.

`graphemeLenAt` is useful if you know / store the previous grapheme end index. Using an index of the grapheme would make the call take linear time each time. [strunicode](https://github.com/nitely/nim-strunicode) works that way, and it goes through the whole string calling `graphemeBounds` every time.

JFYI, in case you want the byte len of every grapheme, you can do this:

```nim
for bounds in text.graphemeBounds:
  echo bounds.b-bounds.a
```

**Comment by eugenesvk** [comment]
Hm, maybe "Return the number of bytes in the grapheme starting at `s[i]`, where `i` is position in bytes, not graphemes, and doesn't respect grapheme boundaries"?

I understand that walking over graphemes is more expensive, it just seems strange that a dedicated grapheme module still gets down to bytes in the general case (that is, a byte-level proc is not an extra "more efficient edition for special cases when you already got the byte position", but the only available proc for getting a grapheme length at a specified position), that's it

By the way, your code gives me **2** for the string example in my original post, instead of **3** bytes
```
for bounds in grTestString.graphemeBounds:
  echo bounds.b-bounds.a
```
...though `echo bounds.len` seems to give the correct **3** bytes value for each slice element

**Comment by nitely** [comment]
> "Return the number of bytes in the grapheme starting at s[i], where i is position in bytes, not graphemes, and doesn't respect grapheme boundaries"

It sounds good.

> it just seems strange that a dedicated grapheme module still gets down to bytes in the general case

It's useful to efficiently limit the length of a string (i.e: truncate) by removing the last grapheme until the string is below the limit. I haven't had the need to randomly access a grapheme.

> By the way, your code gives me 2 for the string example in my original post, instead of 3 bytes

True, needed to add one.

**Comment by eugenesvk** [comment]
Sent a PR with clarification

> It's useful to efficiently limit the length of a string (i.e: truncate) by removing the last grapheme until the string is below the limit. I haven't had the need to randomly access a grapheme

Ok, don't really know myself re. the practicality of the grapheme-based random access
